name: CML & DVC
on: workflow_dispatch
jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: dvc pull dataset
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source activate pytorch_p36
          conda activate DVC
          cd /home/ubuntu
          dvc get https://github.com/toonsquare/sem-pcyc.git DVC/codes.tar
          mv codes.tar /home/model-server/sem_pcyc/dataset
          cd /home/model-server/sem_pcyc/dataset
          ls -al
          echo Done!!
#          tar -xvf intersection.tar
