name: ssh test
on: workflow_dispatch
jobs:

  build:
    name: ssh_Test
    runs-on: self-hosted
    steps:
    - name: executing remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_ID }}
        key: ${{ secrets.PEM_KEY }}
        port: 22
        script: |
          pwd
          whoami
