name: ssh test
on: workflow_dispatch
jobs:

  build:
    name: ssh_Test
    runs-on: self-hosted
    steps:
    - name: executing remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_ID }}
        key_path: ${{ secrets.PEM_KEY_PATH }}
        port: 22
        script: |
          pwd
          whoami
    
    
    
    
    
    
    
#     - env: 
#           PEM_KEY: ${{ secrets.PEM_KEY }}
#           AWS_IP: ${{ secrets.AWS_IP }}
#           AWS_ID: ${{ secrets.AWS_ID }}
#       run: |
#         cd ~
#         pwd
#         ssh ${{ secrets.AWS_ID }}@${{ secrets.AWS_IP }} -i ./${{ secrets.PEM_KEY }}
#         sleep 30s
#         ls
        
        
        
        
        

