name: GitHub Actions self hosted runner
on: workflow_dispatch
jobs:
  jobs1:
      runs-on: self-hosted
      steps:
        - run: |
            source activate pytorch_p36
            cd ~
            cd /home/ubuntu/projects_jonathan
            echo torchserve start!!!!!
#            torchserve --ts-config ./ts/config.properties --start --model-store ./model-store --models sem_pcyc=sem_pcyc2.0.mar
#            sleep 35s
#            echo model request start!!!!!
#            cd ~
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T guitar.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T backyard.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T balloon.jpg
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T car.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T house.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T closet.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T pavillon.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T school.jpg
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T worktable.png
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T bike_racks.jpg
#            sleep 3s
#            curl http://0.0.0.0:8080/predictions/sem_pcyc -T seats.jpg
#            echo job 1 done!!!!!
            
  jobs2:
      needs: jobs1
      runs-on: self-hosted
      steps: 
      - env: 
          PEM_KEY: ${{ secrets.PEM_KEY }}
        run: |
          source activate pytorch_p36
          cd ~
          pwd
          echo ${{ secrets.PEM_KEY }}

    
      

  
        


