name: GitHub Actions self hosted runner
on: workflow_dispatch
jobs:
  build: 
    runs-on: self-hosted
    steps:
      - name: torchserve test
      - run: |
          source activate pytorch_p36
          cd ~
          cd /home/ubuntu/projects_jonathan
          pwd
          
        


