name: test self hosted runner
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - name: torchserve start test
    - uses: actions/checkout@v2
    - run: |
        source activate pytorch_p36
        cd ~
        cd /home/ubuntu/projects_jonathan
        pwd
        torchserve --ts-config ./ts/config.properties --foreground --start --model-store ./model-store --models sem_pcyc=sem_pcyc2.0.mar
        
    - name: torchserve request test
    - run: |
        source activate pytorch_p36
        cd ~
        curl http://0.0.0.0:8080/predictions/sem_pcyc -T guitar.png
        
