name: test self hosted runner
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    - run: |
        whoami
        pwd
        cd ..
        cd ..
        pwd

    
