name: test self hosted runner
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    - run: |
        conda list
        source activate pytorch_p36
        conda list
        pwd
        cd ~
        pwd
        nvidia-smi

    
