on: workflow_dispatch
jobs:
  jobs1:
      runs-on: self-hosted
      steps:
      - env: 
          AWS_IP: ${{ secrets.AWS_IP }}
      - run: |
            source activate pytorch_p36
            cd ~
            curl http://${{ secrets.AWS_IP }}:8081/models/sem_pcyc
